from cmu_graphics import *
import numpy as np
import math
from PIL import Image
import random
import copy

def vec(x, y):
    return np.array([x, y])

class Object:
    def __init__(self, d, v):
        self.d = d
        self.f = vec(0, 0)
        self.v = v

class Black_Hole(Object):
    def __init__(self, d, v, r, image):
        super().__init__(d, v)
        self.MRratio = 10000/3
        self.LRratio = 0.5
        self.image = image
        self.r = r
        self.m = self.r * self.MRratio
        self.limit = self.r + 50 # * (1 + self.LRratio)
        self.angle = 0

    def draw(self):
        x, y = self.d
        drawImage(self.image, float(x), float(y), align = 'center', 
                  width = self.r * 2, height = self.r * 2, rotateAngle = self.angle)

    def simpleDraw(self): # test
        x, y = self.d
        drawCircle(float(x), float(y), self.r)
        endX = float(x) + self.r*math.cos(math.radians(self.angle))
        endY = float(y) + self.r*math.sin(math.radians(self.angle))
        drawLine(float(x), float(y), endX, endY, fill='red', lineWidth = 4) # to show the rotation
    
    def __deepcopy__(self, memo): # This method is generated by ChatGPT
        # Create a new Black_Hole instance with deep-copied attributes
        new_black_hole = Black_Hole(
            copy.deepcopy(self.d, memo),
            copy.deepcopy(self.v, memo),
            self.r,
            self.image  # Skip deep-copying the image
        )
        new_black_hole.MRratio = self.MRratio
        new_black_hole.LRratio = self.LRratio
        new_black_hole.limit = self.limit
        new_black_hole.angle = self.angle
        return new_black_hole
    
class Rocket(Object):    
    def __init__(self, d, v, m, r):
        super().__init__(d, v)
        self.image = CMUImage(Image.open('images/rocket.png'))
        self.m = m
        self.r = r
        self.width = 90
        self.height = 90
        self.f = vec(0, 0)
        self.opacity = 100
    
    def draw(self):
        x, y = self.d
        # position = [float(x), float(y) - 0.5 * self.height, 
        #             float(x) - 0.5 * self.width, float(y) + 0.5 * self.height,
        #             float(x) + 0.5 * self.width, float(y) + 0.5 * self.height]
        # drawPolygon(*position, fill = 'red', rotateAngle = angle)
        drawImage(self.image, float(x), float(y), align = 'center', 
                  width = self.width, height = self.height, opacity = self.opacity) 
    
    def simpleDraw(self): # test
        x, y = self.d
        drawCircle(float(x), float(y), self.r, fill = 'red')
    
    def __deepcopy__(self, memo): # This method is generated by ChatGPT
        # Create a new Rocket instance with deep-copied attributes
        new_rocket = Rocket(
            copy.deepcopy(self.d, memo),
            copy.deepcopy(self.v, memo),
            self.m,
            self.r,
        )
        new_rocket.width = self.width
        new_rocket.height = self.height
        return new_rocket

class Planet: # don't have gravitational effect
    def __init__(self, d, image):
        self.l = 80
        self.d = d
        self.image = None
        self.asked = False
        self.image = image

    def draw(self):
        x, y = self.d
        drawImage(self.image, float(x), float(y), align = 'center', 
                  width = self.l, height = self.l)

class Jupiter(Planet):
    def __init__(self, d, image):
        super().__init__(d, image)
        self.name = 'Jupiter'

class Mars(Planet):
    def __init__(self, d, image):
        super().__init__(d, image)
        self.name = 'Mars'

class Neptune(Planet):
    def __init__(self, d, image):
        super().__init__(d, image)
        self.name = 'Neptune'

class Venus(Planet):
    def __init__(self, d, image):
        super().__init__(d, image)
        self.name = 'Venus'

class Button:
    def __init__(self, cx, cy, w, h, size = 20, text = None): # may have image
        self.cx = cx
        self.cy = cy
        self.w = w
        self.h = h
        self.text = text
        self.image = CMUImage(Image.open('images/button.png'))
        self.size = size
    
    def draw(self):
        drawImage(self.image, self.cx, self.cy, width = self.w, height = self.h, align = 'center')
        if self.text != None:
            drawLabel(self.text, self.cx, self.cy, size = self.size, font = 'orbitron')
    
    def clickOn(self, mouseX, mouseY):
        if (abs(mouseX - self.cx) < self.w/2) and (abs(mouseY - self.cy) < self.h/2):
            return True
        return False

    def __eq__(self, other):
        if self.text == other:
            return True
        return False

class Exit_Button(Button):
    def __init__(self, cx, cy, w, h):
        super().__init__(self, cx, cy, w, h)
        self.cx = 50
        self.cy = 50
        self.w = 50
        self.h = 50
        self.image = CMUImage(Image.open('images/exitbutton.png'))

class Pause_Button(Button):
    def __init__(self, cx, cy, w, h):
        super().__init__(self, cx, cy, w, h)
        self.cx = 730
        self.cy = 50
        self.w = 50
        self.h = 50
        self.paused = False
        
    def draw(self):
        if not self.paused:
            image = CMUImage(Image.open('images/pause.png'))
        else:
            image = CMUImage(Image.open('images/paused.png'))
        drawImage(image, self.cx, self.cy, width = self.w, height = self.h, align = 'center')

class GameOver_Button(Button):
    def __init__(self, cx, cy, w, h):
        super().__init__(self, cx, cy, w, h)
        self.cx = 400
        self.cy = 380
        self.w = 250
        self.h = 50
        self.text = 'Back To Menu'
        self.size = 24

class Auto_Button(Button):
    def __init__(self, cx, cy, w, h, app):
        super().__init__(self, cx, cy, w, h)
        self.cx = 730
        self.cy = 105
        self.w = 130
        self.h = 40
        self.size = 18
        self.text = 'No Jewels'
    
    def draw(self):
        if app.jewels > 0 and not app.auto:
            self.text = 'Auto Drive'
        elif app.auto:
            self.text = 'Exit'
        else:
            self.text = 'No Jewels'
        drawImage(self.image, self.cx, self.cy, width = self.w, height = self.h, align = 'center')
        drawLabel(self.text, self.cx, self.cy, size = self.size, font = 'orbitron')

class Storm:
    def __init__(self, cx, cy):
        self.r = 2
        self.opacity = 100
        self.image = CMUImage(Image.open('images/storm.png'))
        self.cx = cx
        self.cy = cy
    
    def draw(self):
        # drawCircle(self.cx, self.cy, self.r, opacity = self.opacity)
        drawImage(self.image, self.cx, self.cy, width = 3 * self.r, 
                  height = 1.5 * self.r, opacity = self.opacity, align='center')

class Mine:
    def __init__(self, planet, max):
        self.planet = planet
        self.mineButton = Button(185, 630, 210, 35, 17, f'MINE THE {self.planet}')
        self.mine = False
        self.mined = False
        self.mineProgress = 0
        self.fuelGain = 0
        self.mTimer = 0
        self.display = True
        self.display_2 = True
        self.noMineAgain = False
        self.max = max
    
    def draw(self):
        drawImage(CMUImage(Image.open('images/mine.png')),
                  50, 400, width = 270, height = 200)
        self.mineButton.draw()
        if self.mine and 0 < self.mineProgress < 100:
            drawRect(85, 370, self.mineProgress * 2, 11, fill = 'gold')
            drawRect(83, 368, 204, 15, fill = None, border = 'cornflowerBlue', borderWidth = 3)
        elif self.mineProgress >= 100:
            if self.display:
                drawLabel(f'You mined {self.fuelGain} percent of fuel!', 400, 50,
                          size = 22, font = 'orbitron', fill='white', bold=True)
        if self.noMineAgain:
            if self.display_2:
                drawLabel('You can only mine once', 400, 100, 
                          size = 20, font = 'orbitron', bold=True, fill='white')

    def buttonControl(self, mouseX, mouseY):
        if self.mineButton.clickOn(mouseX, mouseY) and not self.mined:
            self.mine = True
        elif self.mineButton.clickOn(mouseX, mouseY) and self.mined:
            self.noMineAgain = True
            self.display_2 = True
    
    def takeMineStep(self, app): 
        if not self.mined and self.mine and self.mineProgress < 100: # mining process
            self.mineProgress += 1
        elif not self.mined and self.mine and self.mineProgress >= 100:
            self.mine = False
            self.mined = True
            self.fuelGain = random.randint(15, self.max) # may change
            if app.fuel + self.fuelGain >= 100:
                app.fuel = 100
            else:
                app.fuel += self.fuelGain
        if self.mineProgress >= 100: # display how much you mine
            self.mTimer += 1
            if self.mTimer >= 50:
                self.display = False
                self.mTimer = 0
                self.mineProgress = 0
        if self.noMineAgain: # display don't mine again
            self.mTimer += 1
            if self.mTimer >= 50:
                self.display_2 = False
                self.mTimer = 0
                self.noMineAgain = False

class QA:
    def __init__(self):
        self.correct = 0 # total correct
        self.total = 0 # total answered
        self.button0 = None
        self.button1 = None
        self.button2 = None
        self.questions = dict()
        self.question = None
        self.star = None
    
    def generateQA(self):
        self.question = random.choice(list(self.questions.keys()))
        answers = self.questions[self.question]
        self.button0 = Button(600, 400, 200, 40, 16, answers[0])
        self.button1 = Button(600, 550, 200, 40, 16, answers[1])
        if len(answers) > 3:
            self.button2 = Button(600, 475, 200, 40, 16, answers[2])
        self.total += 1
    
    def QAdraw(self):
        drawLabel(self.question, 400, 100, size = 20, fill='white', bold=True, font='orbitron')
        drawRect(400, 130, 700, 10, fill='cornSilk', align='center')
        drawPolygon(220, 130, 240, 130, 230, 185, fill='cornSilk')
        if self.button0 != None:
            self.button0.draw()
            self.button1.draw()
        if self.button2 != None:
            self.button2.draw()
    
    def mouseControl(self, mx, my, app):
        if self.button0.clickOn(mx, my):
            self.check(self.button0, app)
        elif self.button1.clickOn(mx, my):
            self.check(self.button1, app)
        elif self.button2 != None and self.button2.clickOn(mx, my):
            self.check(self.button2, app)

    def check(self, button, app):
        if self.isCorrect(button):
            self.correct += 1
            app.jewels += 100
            self.button2 = None
        else:
            self.button2 = None
        if self.total < 3:
            self.questions.pop(self.question)
            self.generateQA()
        else:
            setActiveScreen(self.star + 'End')
    
    def isCorrect(self, button):
        correctIndex = self.questions[self.question][-1]
        if button == self.questions[self.question][correctIndex]:
            return True
        return False

    def endDraw(self):
        if self.correct == 0:
            drawLabel('You got it all wrong!', 400, 80, size = 35, fill='white', font='orbitron')
            drawLabel('Go back to your ship.', 400, 130, size = 35, fill='white', font='orbitron')
        elif self.correct == 1:
            drawLabel('You only got one right.', 400, 80, size = 35, fill='white', font='orbitron')
            drawLabel("Here's 100 pounds of jewels for you.", 400, 130, size = 35, fill='white', font='orbitron')
        elif self.correct == 2:
            drawLabel('You got two right.', 400, 80, size = 35, fill='white', font='orbitron')
            drawLabel("Here's 200 pounds of jewels for you.", 400, 130, size = 35, fill='white', font='orbitron')
        elif self.correct == 3:
            drawLabel('You got it all right!', 400, 80, size = 35, fill='white', font='orbitron')
            drawLabel("Here's 300 pounds of jewels for you.", 400, 130, size = 35, fill='white', font='orbitron')

class VenusQA(QA):
    def __init__(self):
        super().__init__()
        # The questions and answers in the following dictionary are generated by ChatGPT
        self.questions = {'Which planet is Venus in terms of its distance from the Sun?':['First','Third','Second',2],
                     "Venus is often called Earth's 'sister planet'":['True','False',0],
                     "What is the primary component of Venus's atmosphere?":['Carbon Dioxide','Nitrogen','Methane',0],
                     'Venus has no moons.':['True','False',0],
                     'What is the surface temperature of Venus typically higher than?':['300°C','650°C','450°C',2],
                     'Venus is equivalent to the Greek goddess Aphrodite.':['True','False',0],
                     'Who is the son of Venus, often depicted as carrying a bow and arrow?':['Apollo','Jupiter','Cupid',2],
                     'The Roman goddess Venus was the ancestor of the Roman people.':['True','False',0],
                     'What is Venus often depicted with in classical art?':['A bow and arrow','A shield and sword','A dove or seashell', 2]}
        self.star = 'Venus'
    
class NeptuneQA(QA):
    def __init__(self):
        super().__init__()
        # The questions and answers in the following dictionary are generated by ChatGPT
        self.questions = {'Which planet is Neptune in terms of its distance from the Sun?': ['Eighth', 'Seventh', 'Sixth', 0],
                        'Neptune is the densest gas giant in the Solar System.': ['True', 'False', 1],
                        'What is the largest moon of Neptune called?': ['Europa', 'Triton', 'Ganymede', 1],
                        'Which of these is a unique feature of Neptune’s atmosphere?': ['Auroras', 'The Great Red Spot', 'The Great Dark Spot', 2],
                        'What is Neptune’s average orbital period around the Sun?': ['165 Earth years', '88 Earth years', '12 Earth years', 0],
                        'Neptune is the Roman god of which domain?': ['The underworld', 'The sea', 'The sky', 1],
                        'Neptune is considered equivalent to the Greek god Poseidon.': ['True', 'False', 0],
                        'What is Neptune commonly depicted holding in Roman mythology?': ['A lightning bolt', 'A sword', 'A trident', 2],
                        'In Roman mythology, Neptune is the brother of which god?': ['Apollo', 'Mars', 'Jupiter', 2],
                        'Neptune was also associated with horses in Roman mythology.': ['True', 'False', 0]}
        self.star = 'Neptune'